### ISSUE TITLE
Remove existing widgets on import

### ISSUE THREAD

**Issue by UnitedThemes** [stevengliebe/widget-importer-exporter#4]
Hi,

is there a way to remove the existing widgets from a sidebar when importing? WordPress puts default widgets into the first sidebar by default. But we'd like to remove them when using the importer. Is this possible?

**Comment by stevengliebe** [comment]
Hello,

There is no feature in the plugin for deleting existing widgets.

What you could do is use the wie_after_import action to automatically delete them after the import.

**Comment by UnitedThemes** [comment]
Hi,

thanks for coming back to us that quickly and sorry about the wrong label. However, isn't there a point where the tool grabs the existing widgets from sidebar ID XY and injects the new ones? Thanks in advance.

**Comment by stevengliebe** [comment]
It checks existing widgets against widgets to be imported and if any are the same (and in the same sidebar), they are not imported. No deletion occurs.

You can browse the code here. It is pretty well commented to explain what happens at each stage.

https://github.com/stevengliebe/widget-importer-exporter/blob/master/includes/import.php

**Comment by UnitedThemes** [comment]
Hi,

thanks for clarification! We really appreciate it !

UT
