### ISSUE TITLE
Widget format is lost upon import

### ISSUE THREAD

**Issue by signcarver** [stevengliebe/widget-importer-exporter#5]
I can export and then import the widget data from one site to another. However the widget format is lost upon import. Please see attached image.
![widget-import-export-050615](https://cloud.githubusercontent.com/assets/608787/7503493/6081ca4e-f411-11e4-97b9-ab63bc96cd66.jpg)

**Comment by stevengliebe** [comment]
Hello,

When you go to Appearance > Widgets on the new site and view the widget's settings, do they differ from the widget's settings on the original site?

The code in the screenshot I assume is generated by the theme or plugin that provides the widget. What I'd like to know is if the data being imported/exported is different after import. Comparing the widget's settings in your admin areas for the new and old site should reveal this.

**Comment by signcarver** [comment]
Hey Steven,
The Appearance > Widgets data matches on both sites.

Steve R.

**Comment by stevengliebe** [comment]
In that case, I recommend presenting the display issue to the theme or plugin maker that is providing the widget since that is what is producing the output. All the widget importer does is move the data. If the data is identical then it seems the issue is on the output end.

**Comment by signcarver** [comment]
OK, thank you! I am using a plugin call "Image Widget". I have asked the question on their support site.

Thank you for your help!

**Comment by stevengliebe** [comment]
Good luck getting it fixed!
